### ISSUE TITLE
Lack of compatibility/installation information.

### ISSUE THREAD

**Issue by martinhbramwell** [OCA/geospatial#1]
There is neither information about which Odoo versions will allow GeoSpatial to run correctly, nor a link to a complete installation procedure (or "getting started")  document, nor a dependencies list (PostGIS?).

**Comment by ovnicraft** [comment]
AFAIK run ok with 6.1, C2C company release a survey to improve 7.0 version.
https://www.camptocamp.com/en/actualite/openerp-geoengine-your-map-view-for-openerp-7-0-and-8-0/

**Comment by nbessi** [comment]
Hello 

There is a doc folder inside the repository, with the documentation. At that time only version 6.1 of odoo is fully supported. I have planned to use github wiki for the documentation. It will be udpated beginig of august, after the holidays period.

Regards

**Comment by nbessi** [comment]
I forgot to post the documentation link:

https://github.com/OCA/geospatial/tree/6.1/base_geoengine/doc/source

Regards

**Comment by ovnicraft** [comment]
@nbessi any date planned to test at 7.0 ?

**Comment by nbessi** [comment]
@ovnicraft 

Previous versions of Geoengine were more based on a prototype approach to understand user needs.

For the future of the module we have two main trends

# Major Evolution And Refactor:

 It will be based on functional needs and experience that have been gathered.
  In order to do this, ressource has to be found.

Following options seems reasonable.
- Doing a crowd funding 
- Getting more people who want to participate especially JS dev and SIG dev.

# Straight Maintenance:

The code base will be ported 1to1 only cleanup and mandatory refactoring will be done.
Support of new API is also one of the slow evolution goal.

The roadmap who will be taken will heavily depends on the resource the project will be able to get.

**Comment by ovnicraft** [comment]
@nbessi in our company we are really interested we have gov customers  who have odoo and GIS systems to manage land registers we have 2 options integrate with a new django app or do it on odoo we can dedicate a one full time resource for this.
So i stay tuned here.

Thanks for spatial !

**Comment by ovnicraft** [comment]
@nbessi Any news about 7.0 ?

**Comment by nbessi** [comment]
Hello, 

At that time there is not enough resources available for the project.
GIS is a really specific domain and there is not a lot of people that know
Odoo and GIS. Without a concrete  funding, resources the project will probably stay on minimal activity level for a while.

At that time for OCA, I am mostly engaged on the port of the swiss localisation for V8.0 

Once finished, I will came back to the spatial addons. The fund raise is still in the pipe but target is the version 8.0. Any help is welcome as I'm not an expert in the domain.

@ovnicraft for version 7.0 there will probably not be a lot of investment except to be iso functional with 6.1.  Any resources are welcome, and I will review any patch. 

I'm looking for more maintainers and steering members. If you are interested It would be nice to propose yourself as a steering member of the project.

Regards

Nicolas

**Comment by ovnicraft** [comment]
@nbessi I am reading code and checking this, let me first has better control over geoengine then i will make a PR an you help me on this.

**Comment by nbessi** [comment]
@ovnicraft cool :)

**Comment by codeadict** [comment]
Any advance on that @nbessi @rvalyi @ovnicraft im also interested on help i see a 7.0 branch here is this functional??

**Comment by ovnicraft** [comment]
@codeadict not yet, i am working on but i have not time this week, i could push in next week.

**Comment by codeadict** [comment]
Any good advance, can we create issues to define scope and work on this and not work on same stuff
