### ISSUE TITLE
Place multiples models in one view

### ISSUE THREAD

**Issue by williamcastrillon** [OCA/geospatial#100]
Hi,
I'm trying to show three models data in one view, according to [this post](https://www.odoo.com/es_ES/forum/ayuda-1/question/place-two-models-on-one-view-12350) the better way is to create another model that is populated by a SQL View that joins the three models, I did it, like the post says, the module installs succesfully, but when I try to view the information through the model form view. I got this error:

> File "/opt/odoo/server/addons/web/controllers/main.py", line 936, in _call_kw
>     return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
> AttributeError: 'geo.point.alert.route' object has no attribute 'get_edit_info_for_geo_column' 

and when I try the GeoEngine View, I got this:

> TypeError: data.geoengine_layers is undefined
> 
> http://myserver:8069/web/js/web.assets_common/83f954b:4191

my module code looks like this:

```
class EpiiGeoPointAlertRoute(models.Model):
    _name = "geo.point.alert.route"
    _auto = False
    _order = "date DESC"
    #model_id = fields.Integer('ID', readonly=True)
    model_type = fields.Char('Tipo', size=32, readonly=True)
    geo_point = geo_fields.GeoPoint('Punto', readonly=True)
    geo_alert = geo_fields.GeoPoint('Alerta', readonly=True)
    note = fields.Char('Observacion', size=32, readonly=True)
    alert = fields.Selection([('on', 'Encendido'),
                                ('off', 'Apagado'),
                                ('Warn', 'Pánico')],
                                'State',
                                readonly=True)
    route = geo_fields.GeoLine('Recorrido', readonly=True)#sales route
    date = fields.Datetime('Fecha', readonly=True)
    day = fields.Integer('Día', readonly=True)
    month = fields.Integer('Mes', readonly=True)
    year = fields.Integer('Año', readonly=True)

    def init(self, cr):
        tools.sql.drop_view_if_exists(cr, 'geo_point_alert_route')
        cr.execute("""
            CREATE view geo_point_alert_route as
                --SELECT *, row_number() OVER (ORDER BY date ASC) AS id
                --FROM
                (
                    SELECT (p.id*100) as id,
                    'point' as model_type,
                    p.geo_point,
                    NULL::geometry(Point,900913) as geo_alert,
                    p.note,
                    p.date,
                    NULL as alert,
                    NULL::geometry(LineString,900913) as route
                    FROM geo_point p

                UNION

                    SELECT (a.id*10000) as id, 
                    'alert' as model_type,
                    NULL::geometry(Point,900913) as geo_point,
                    a.geo_point as geo_alert,
                    a.note,
                    a.date,
                    a.alert,
                    NULL::geometry(LineString,900913) as route
                    FROM geo_alert a

                UNION

                    SELECT (r.id*1000000) as id, 
                    'route' as model_type,
                    NULL as geo_point,
                    NULL as geo_alert,
                    NULL as note,
                    r.date,
                    NULL as alert,
                    r.route
                    FROM geo_route r
                )
        """)
```

any idea on how can I solve this?

**Comment by yvaucher** [comment]
Hello @williamcastrillon have you defined a vector layer in xml for all your geofields ?

You need to define one per geo fields. And as you create a new model here those are new fields even if already defined on your 3 other models.

Something like that for your model `geo.point.alert.route`
https://github.com/OCA/geospatial/blob/9.0/base_geoengine_demo/zip_view.xml#L63-L70

**Comment by SimonFalesse** [comment]
I allow myself to relaunch this topic in order to know if finally, it was possible to display on a single map, several classes of objects with different markers (point, multilines, multipolygons, ...)?
