### ISSUE TITLE
Is the Partner geo location manually editable?

### ISSUE THREAD

**Issue by dreispt** [OCA/geospatial#126]
I'm testing the `geoengine_partner` module, and I was expecting to be able to manually set the Partner's location by clicking on the Geoengine Map.
But it seems to be readonly.

Is there some way to manually edit point geo locations, or is it a geoengine limitation?

Thanks!

**Comment by dreispt** [comment]
Ping!

**Comment by dreispt** [comment]
Ping!

**Comment by yvaucher** [comment]
Geoengine widget is designed for edition since Odoo 8.0. In previous version we could just insert lat long.

Not sure about geoengine_partner. You might find a useful exemple in base_geoengine_demo module.

Which version of the module are you using ?

**Comment by dreispt** [comment]
I was trying 8.0.
`geoengine_parter` adds a [GeoPoint](https://github.com/OCA/geospatial/blob/8.0/geoengine_partner/geo_partner.py#L30) to the model and [form view](https://github.com/OCA/geospatial/blob/8.0/geoengine_partner/geo_partner_view.xml#L11).

I'm supposed to be able to set a value on it by clicking on a point in the map widget, correct?

**Comment by yvaucher** [comment]
@dreispt To be able to add or modify a point you must be in edit mode on your form view (maybe that was just that ?)

**Comment by dreispt** [comment]
I'm quite sure I was, but I'll try that again.

--dr 

No dia 16/02/2017, às 15:07, Yannick Vaucher <notifications@github.com> escreveu:

**Comment by yvaucher** [comment]
@dreispt This might also be another of those bug related to widget being instantiated in a tab I had to get rid of in version 9.0.

For example one issue was that you would see the map belonging to another record when switching from a partner (or other object) to another.

Maybe try to move the geoengine widget outside of tabs to see if it works.

**Comment by yvaucher** [comment]
@dreispt didn't had an environment for 8.0, thus I prefered to migrate it to 9.0 and test it

-> https://github.com/OCA/geospatial/pull/128

Thus I checked that in 9.0 I can edit create / edit / remove a point. Just had to drop the google raster layer to replace it by OSM.

**Comment by dreispt** [comment]
@yvaucher I tested it locally on 8.0 and I was able to move the point using the map, although the usability was not nice: the map point moves were displaced from the mouse cursor position. That could be related to the bugs you mentioned.

**Comment by yvaucher** [comment]
@dreispt That's mainly why we moved to Openlayers 3 for Odoo 10.0 (there is also a branch for 9.0)
