### ISSUE TITLE
[RFC] geoengine_location: Support base_location

### ISSUE THREAD

**Issue by lasley** [OCA/geospatial#136]
This module will provide geoengine support to the `better.zip` model that is provided in `base_location`. It will automatically install if both `base_geongine` & `base_location` are installed.

I have added `latitude` and `longitude` fields to `base_location` in https://github.com/OCA/partner-contact/pull/405, but they are just plain floats. Upon installation, this module will need to use the existing lat/long to create a geopoint using [`GeoPoint.from_latlon`](https://github.com/OCA/geospatial/blob/10.0/base_geoengine/fields.py#L197).

This module will add a stored [computed field `geo_point` to `better.zip` with an empty inverse](https://github.com/OCA/geospatial/issues/136#issuecomment-294280533). To that end, the above install hook could utilize this method to update the pre-existing records in the db.

It will also add an onchange for the point in order to automatically identify the correct zip_id, as described in https://github.com/OCA/geospatial/issues/136#issuecomment-298606090.

At this time, I don't think that it makes sense to provide a view for this. I'm open to hear out some use cases that would sway my mind though, if someone has them.

Anyone have thoughts on this?

**Comment by lmignon** [comment]
@lasley why do you want to hook the create and write method from better.zip? Your geopoint should be a computed field and if you want to allow the user to directly specify a geopoint you can declare an empty inverse method...

**Comment by lasley** [comment]
@lmignon TBH I have no idea why I didn't think of that, thanks for pointing it out! RFC updated

**Comment by yvaucher** [comment]
By the way, as a side note, the onchange works also on geoengine widget, thus adding a point can trigger an onchange and use a geo_domain: `[('area', 'geo_contains', point)]`

It would be useful if you have the area of your zip locations.

Example which should work (based on a module I made for a customer with other models)

``` python
    @api.onchange('point')
    def onchange_geo_point(self):
        for record in self:
            if record.point:
                x, y = geojson.loads(record.point).coordinates
                point = "POINT({} {})".format(x, y)
                zip_id = self.env['res.better.zip'].geo_search(
                    geo_domain=[('area', 'geo_contains', point)],
                    limit=1
                )
                if zip_id:
                    record.zip_id = zip_id[0]
```

**Comment by lasley** [comment]
Excellent idea, thanks @yvaucher! RFC updated

**Comment by lasley** [comment]
Closing to track in #151
