### ISSUE TITLE
About Satellite Imagery

### ISSUE THREAD

**Issue by dek-odoo** [OCA/geospatial#138]
Hello Guys,

Is there any possibility of having satellite imagery in future versions ?
If not, what would it take to implement one ?
If google is not possible, can there be some other source of satellite Imagery ?

Without this feature, one gets one more reason on not using odoo.
Can there be a branch that has satellite imagery in case somebody wants to see/test ?

I have already looked at the issues like, https://github.com/OCA/geospatial/issues/63.
Sorry about having so many questions.
Thank you.

**Comment by dek-odoo** [comment]
@yvaucher

**Comment by yvaucher** [comment]
Hello @dek-odoo 

There is no plan to add one in future version.
But it is completely doable. You need to define a raster layer and configure a WMTS service.
You have an example in https://github.com/OCA/geospatial/tree/10.0/geoengine_maplausanne on how to implement such module.

**Comment by dek-odoo** [comment]
Ok. Thanks a lot.

**Comment by dek-odoo** [comment]
@yvaucher 

OpenLayers seems to be undefined on several places.

Like
>[https://github.com/OCA/geospatial/blob/9.0-ol3/base_geoengine/static/src/js/views/geoengine_common.js#L51](url)

>[https://github.com/OCA/geospatial/blob/9.0-ol3/base_geoengine/static/src/js/views/geoengine_common.js#L56](url)

Thank you.
