### ISSUE TITLE
odoo patch

### ISSUE THREAD

**Issue by yelizariev** [OCA/geospatial#149]
If I understand correctly, patch was merged to odoo. So the note should be removed from documentation:

> In order to be able to create geometries, you will need to apply this patch on official Odoo branch (OCB is already patched): https://github.com/odoo/odoo/pull/10639

**Comment by yvaucher** [comment]
Indeed, we removed the patch here from CI:
https://github.com/OCA/geospatial/commit/4068cff42b488a67e25a027c28e84f49506cde8c

Can you point me the file in which we still have this sentence ?

**Comment by yelizariev** [comment]
README: https://github.com/OCA/geospatial/blob/10.0/README.md
website: http://oca.github.io/geospatial/installation.html

**Comment by yvaucher** [comment]
Fixed at 540e938acaf7a59e114fec35ebb39c5ef35a0c58

**Comment by yelizariev** [comment]
What about website? 
https://github.com/OCA/geospatial/blob/gh-pages/_sources/installation.txt
http://oca.github.io/geospatial/installation.html
