### ISSUE TITLE
Unable to use map symbols feature

### ISSUE THREAD

**Issue by bouchezb** [OCA/geospatial#153]
Hi,

I'm trying to use symbols with my layers and i can't make it work.
I've seen there is a [patch](http://gitlab.opengest.solutions/OCA/geospatial/commit/49c42c211fe26c08c61739fbae9c3c325f3b67ab?w=1) for v9.0 with broken symbol feature.

As you can see this is a 2 year old patch which seems to fix the bug in V9 and v10, but in the current V10 i can't see modifications for th file "geoengine_view.js"
Seems that symbols are read, but not used for final map styling.

old patch [geoengine_view.js](http://gitlab.opengest.solutions/OCA/geospatial/blob/49c42c211fe26c08c61739fbae9c3c325f3b67ab/base_geoengine/static/src/js/views/geoengine_view.js) uses "createMultiSymbolStyle" function

```
            case "basic":
                if (!cfg.symbols) {
                    break;
                }
                if (cfg.symbols.length > 0) {
                    style = this.createMultiSymbolStyle(cfg.symbols);
                    vl.styleMap = new OpenLayers.StyleMap({
                        'default': style,
                    });
                }
                break;
```
but [current JS file](https://github.com/OCA/geospatial/blob/10.0/base_geoengine/static/src/js/views/geoengine_view.js) is not because basic representation uses radius styling
```
           default: // basic
                var fill = new ol.style.Fill({
                    color: begin_color
                });
                var stroke = new ol.style.Stroke({
                    color: '#333333',
                    width: 1
                });
                var styles = [
                    new ol.style.Style({
                      image: new ol.style.Circle({
                        fill: fill,
                        stroke: stroke,
                        radius: 5
                      }),
                      fill: fill,
                      stroke: stroke
                    })
                ];
                return {
                     style : function(feature, resolution) {
                          return styles;
                     },
                    legend: ''
                };
```

Thanks.

**Comment by MagnusKriel** [comment]
Hi,
This seems to be broken still. Anyone planning to get this fixed?
(I'm using Odoo 11)
