### ISSUE TITLE
[10] convert lat/long in GEoPoint

### ISSUE THREAD

**Issue by flammiag** [OCA/geospatial#154]
Hi, 
i'm working with android and Odoo. 
From Android, i receive the gps coordinate in LatLong. 

How do i can Convert this lat/long in GeoPoint ?
I need the GeoPoint because i use geoSearch for verify if the geopoint is contained in the GeoMultiPolygon.

**Comment by yvaucher** [comment]
This is a matter of projection, I think I already answered on the mailing list. Thus I close this.
