### ISSUE TITLE
ir.ui.view not editable due to field vector_layer_ids set as required

### ISSUE THREAD

**Issue by dek-odoo** [OCA/geospatial#157]
Impacts all versions.

The module base_geoengine inherits ir.ui.view and adds a few fields.
One of the fields **`vector_layer_ids` is set to `required=True`**
> https://github.com/OCA/geospatial/blob/10.0/base_geoengine/geo_view/ir_view.py#L30

And in views, **the field** is declared in a page that is **displayed based on condition**. i.e. If the the view is not `geoengine`, the field should not be displayed.
> https://github.com/OCA/geospatial/blob/10.0/base_geoengine/geo_view/ir_view_view.xml#L20
> https://github.com/OCA/geospatial/blob/10.0/base_geoengine/geo_view/ir_view_view.xml#L12

So the rest of the views can not be edited. :grin::wink:

The problem has been reported several times at OCA Community Mailing list.
> https://odoo-community.org/groups/geospatial-48/geospatial-38717
> https://odoo-community.org/groups/geospatial-48/geospatial-66367

**Comment by dek-odoo** [comment]
@yvaucher

**Comment by yvaucher** [comment]
IIRC required attribute had no impact on old version of Odoo with x2many.

Thus said, indeed we don't want to add required fields on standards views.
Can you create a PR to solve this ?
