### ISSUE TITLE
Printing multipolygon field

### ISSUE THREAD

**Issue by estebanjuela** [OCA/geospatial#158]
Is there any way to print a multipolygon field with qweb or any other way ?. When i try to put the field on report, the pdf file only shows the coordinates.  I need that the pdf shows the map as background and the polygon.

MULTIPOLYGON (((-8696217.733325399 -256928.3818698107, -8696192.6524255 -256931.9648555108, -
8696197.429739701 -256967.7947125108, -8696226.0936253 -256959.434412551, -8696217.733325399 -
256928.3818698107)))

Thanks

**Comment by yvaucher** [comment]
No, this would be a great feature, but currently not possible as not implemented.

What you see is string format of the field.
