### ISSUE TITLE
Map view on mobile device

### ISSUE THREAD

**Issue by ecino** [OCA/geospatial#169]
Hi,
On mobile device, the geoengine map displays well but it's hard-to-impossible to click on a dot and open the popup that shows informations on a record. I don't know if it's related to openstreetmap or the implementation in Odoo, but that would be great if the usability could be improved for mobile devices.

**Comment by yvaucher** [comment]
@ecino I suppose you mean openlayers instead of openstreetmap.

There are some default handling in openlayers, but haven't tested them.
May I ask you which version of geoengine (and thus openlayers) you used?

**Comment by ecino** [comment]
@yvaucher I'm not sure which version it is, we used the default one which is coming when installing module `geoengine_partner`, on the map of the customers. We are using it on Odoo 10.

**Comment by yvaucher** [comment]
@ecino thus your are using OL3
https://github.com/OCA/geospatial/tree/10.0/base_geoengine/static/src/js/lib

This is the only lead I can give you for now. To test if it can be solved by altering the CSS to have larger dots.
Maybe I can have a look at that later but not before a couple of weeks. Let me know if you find any solution.
