### ISSUE TITLE
how add an get position plugin in  the map

### ISSUE THREAD

**Issue by lizhi2013** [OCA/geospatial#171]
when using in phone，get position functio is often need to user，how can add this function

**Comment by yvaucher** [comment]
I don't think it comes as default in Openlayers. And nothing was done for that in geoengine.

It looks like you need to use the browser geolocation API to get current location from your mobile device.
https://www.w3schools.com/html/html5_geolocation.asp

For using a location and send it to share it or use it with a GPS app I'm also pretty sure it's not in openlayers by default. It would require an additional control on the map to do that. There are probably some js libraries for that out there. The simplest way to do it might be to create a link like: `https://maps.google.com/maps?q=[latitude],[longitude]`

**Comment by yvaucher** [comment]
@lizhi2013 a follow up to your question.

Here you can find an example with Openlayers using a function that wrap browser's html5 geolocation.

https://openlayers.org/en/latest/examples/geolocation.html?q=geoloc
