### ISSUE TITLE
V7.0: VIEW_TYPE - Side Effect !!! #9

### ISSUE THREAD

**Issue by diassynthesis** [OCA/geospatial#172]
Still the same issue after 3 years.
@benwillig i can't find this commit.

**Comment by pedrobaeza** [comment]
@diassynthesis and it's going to take more if you don't specify correctly things. And even that, this is a voluntary work, so no requirement of doing anything.

**Comment by diassynthesis** [comment]
@pedrobaeza It's in the title: VIEW_TYPE - Side Effect !!! #9

an old issue !
