### ISSUE TITLE
V7.0: VIEW_TYPE - Side Effect !!! #9

### ISSUE THREAD

**Issue by diassynthesis** [OCA/geospatial#173]
@pedrobaeza It's in the title (#9): VIEW_TYPE - Side Effect !!! #9

an old issue !

**Comment by diassynthesis** [comment]
@Github Just give us a way to reopen a closed issue ... instead of duplicating a issue

https://github.com/isaacs/github/issues/583

https://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github

**Comment by pedrobaeza** [comment]
No, sorry, but the case in ended and opening new ones you are not going to get anything

**Comment by diassynthesis** [comment]
OK, I'll reopen a new one.
Thanks.
