### ISSUE TITLE
V7.0: CONFLICT!!!

### ISSUE THREAD

**Issue by diassynthesis** [OCA/geospatial#174]
Now, after some modifications i can install base_geoengine module (i will submit a PR for V7.0).
But there is a strange issue after installing it.
All seems to working fine, but when restarting the server, i get the following error(and I can no longer log me into the server):
-------Start Error Log:
File "/usr/lib/pymodules/python2.7/openerp/osv/orm.py", line 948, in create_instance
obj.init(pool, cr)
File "/usr/lib/pymodules/python2.7/openerp/addons/web_dynatree/base.py", line 98, in init
self._columns['type'].selection.append(VIEW_TYPE)
AttributeError: 'tuple' object has no attribute 'append'
-----End Log----

Steps to reproduce:
1- install web_dynatree (from [bitbucket.org/anybox/web_dynatree](https://bitbucket.org/anybox/web_dynatree/src))
2- install base_geoengine
3- restart OpenERP
![bug-view_type](https://user-images.githubusercontent.com/3822648/45985077-67744f00-c05c-11e8-9a5e-7e0537e3cc9f.png)

This is also the case with the following modules:
[web_nvd3_chart](bitbucket.org/anybox)
web_dynatree_visual_export
[booking_chart](https://github.com/trobz/openerp-booking-chart/tree/7.0)

When no one of the above modules are installed, i can install base_geoengine, and after that if i try to install any one of those modules i run in the same issue :

self._columns['type'].selection.append(VIEW_TYPE)
AttributeError: 'tuple' object has no attribute 'append'

After that, the only way for me to get OpenERP working again is to delete the related module from the addons folder, restart OpenERP, uninstall base_geoengine, restore the deleted module ....

Any idea ?

**Comment by pedrobaeza** [comment]
The error is on web_dynatree module, not on geoengine.
