### ISSUE TITLE
[9.0] Problem with WMS map

### ISSUE THREAD

**Issue by Killance** [OCA/geospatial#186]
Hello,

I’m trying the demo module of geospatial in V9 and I notice that the opening of a view that content a WMS distant map generates a JS error. 

Odoo Client Error

TypeError: null is not an object (evaluating 'this.baseLayer.wrapDateLine')
http://localhost:8069/web/content/280222-ea63d9a/web.assets_backend.js:4462

Traceback:
zoomToExtent@http://localhost:8069/web/content/280222-ea63d9a/web.assets_backend.js:4462:54
render_map@http://localhost:8069/web/content/280222-ea63d9a/web.assets_backend.js:7105:229
http://localhost:8069/web/content/280222-ea63d9a/web.assets_backend.js:7096:579
http://localhost:8069/web/content/279891-dc2b89c/web.assets_common.js:650:686
fire@http://localhost:8069/web/content/279891-dc2b89c/web.assets_common.js:644:304
fireWith@http://localhost:8069/web/content/279891-dc2b89c/web.assets_common.js:649:202
http://localhost:8069/web/content/279891-dc2b89c/web.assets_common.js:651:56
fire@http://localhost:8069/web/content/279891-dc2b89c/web.assets_common.js:644:304
fireWith@http://localhost:8069/web/content/279891-dc2b89c/web.assets_common.js:649:202
http://localhost:8069/web/content/279891-dc2b89c/web.assets_common.js:650:874
fire@http://localhost:8069/web/content/279891-dc2b89c/web.assets_common.js:644:304
fireWith@http://localhost:8069/web/content/279891-dc2b89c/web.assets_common.js:649:202
http://localhost:8069/web/content/279891-dc2b89c/web.assets_common.js:650:874
fire@http://localhost:8069/web/content/279891-dc2b89c/web.assets_common.js:644:304
fireWith@http://localhost:8069/web/content/279891-dc2b89c/web.assets_common.js:649:202
done@http://localhost:8069/web/content/279891-dc2b89c/web.assets_common.js:1040:106
callback@http://localhost:8069/web/content/279891-dc2b89c/web.assets_common.js:1060:23

Is it a bug or I do something wrong ? I want to use this kind of map in the futur.

Thanking you in advance

**Comment by guewen** [comment]
> a WMS distant map generates a JS error.

What is exactly a WMS distant map? A custom WMS that you added?
If so, can you show what you did?

This error `null is not an object (evaluating 'this.baseLayer.wrapDateLine')` indicates that `baseLayer` is null. At some point in geoengine_view.js / geoengine_widget.js, there is a call to `this.map.addLayer(...)`. This is where you want to be sure that you inject the layer properly.

**Comment by Killance** [comment]
Hello Guewen,

WMS distant is a raster layer type of base geoengine, not a custom.

Lancelot

**Comment by yvaucher** [comment]
@Killance Hello,

Thanks for reporting. Could you reproduce it by using ?debug= in the url to have a comprenhensive trace back? Here all libs are concat in common and backend js files which won't tell use much about the error.

IIRC corretly `?debug=assets` did not exist in Odoo 9.0 but according to the doc it should work with simply being in debug mode. https://www.odoo.com/documentation/9.0/howtos/web.html

**Comment by Killance** [comment]
Hi @yvaucher,

Thank you for your answer. I obtain another error message in debug mode :

TypeError: null is not an object (evaluating 'this.format.read')
http://localhost:8069/base_geoengine/static/src/js/views/geoengine_widgets.js:135

Traceback:

set_value@http://localhost:8069/base_geoengine/static/src/js/views/geoengine_widgets.js:135:43
http://localhost:8069/web/static/src/js/framework/class.js:89:43
http://localhost:8069/web/static/src/js/views/form_view.js:369:41
forEach@http://localhost:8069/web/static/lib/underscore/underscore.js:150:17
http://localhost:8069/web/static/lib/underscore/underscore.js:1484:39
load_record@http://localhost:8069/web/static/src/js/views/form_view.js:366:28
load_record@http://localhost:8069/web_edit_form_conditionable/static/src/js/views.js:76:20
http://localhost:8069/web/static/src/js/framework/class.js:122:43
trigger@http://localhost:8069/web/static/src/js/framework/mixins.js:222:36
trigger@http://localhost:8069/web/static/src/js/framework/mixins.js:272:47
http://localhost:8069/web/static/src/js/views/form_view.js:341:33
http://localhost:8069/web/static/lib/jquery/jquery.js:3276:94
fire@http://localhost:8069/web/static/lib/jquery/jquery.js:3119:63
fireWith@http://localhost:8069/web/static/lib/jquery/jquery.js:3231:53
http://localhost:8069/web/static/lib/jquery/jquery.js:3283:104
fire@http://localhost:8069/web/static/lib/jquery/jquery.js:3119:63
fireWith@http://localhost:8069/web/static/lib/jquery/jquery.js:3231:53
http://localhost:8069/web/static/lib/jquery/jquery.js:3283:104
fire@http://localhost:8069/web/static/lib/jquery/jquery.js:3119:63
fireWith@http://localhost:8069/web/static/lib/jquery/jquery.js:3231:53
http://localhost:8069/web/static/lib/jquery/jquery.js:3321:62
fire@http://localhost:8069/web/static/lib/jquery/jquery.js:3119:63
fireWith@http://localhost:8069/web/static/lib/jquery/jquery.js:3231:53
http://localhost:8069/web/static/lib/jquery/jquery.js:3283:104
fire@http://localhost:8069/web/static/lib/jquery/jquery.js:3119:63
fireWith@http://localhost:8069/web/static/lib/jquery/jquery.js:3231:53
http://localhost:8069/web/static/lib/jquery/jquery.js:3283:104
fire@http://localhost:8069/web/static/lib/jquery/jquery.js:3119:63
fireWith@http://localhost:8069/web/static/lib/jquery/jquery.js:3231:53
done@http://localhost:8069/web/static/lib/jquery/jquery.js:9275:53
callback@http://localhost:8069/web/static/lib/jquery/jquery.js:9685:65
