### ISSUE TITLE
Error on travis right (9.0)

### ISSUE THREAD

**Issue by BenjaHe** [OCA/geospatial#191]
Hello,

I created the very simple pull request #190 which failed because the DB user is not allowed to create extension postgis and postgis_topology.

May you merge it or solved the problem?

Thank you

**Comment by Sixologue** [comment]
Thank you, How could I do it?

**Comment by BenjaHe** [comment]
I have no idea of how to accept pull request :-(
I think you need the write access to the project geospatial to do it

**Comment by yvaucher** [comment]
Approval rules are:

at least 2 approvals and 5 working days
or to fast track 3 approvals.
