### ISSUE TITLE
Edit, Add Multipolygon in web view

### ISSUE THREAD

**Issue by brian10048** [OCA/geospatial#197]
Is there currently a way to draw more than one polygon shape in a multipolygon field? v11 and v12

For example:

### Action:
When editing a field type of MultiPolygon in the web view

### Expected Result
Receive a toolbox allowing to draw multiple polygons on a map which creates a record similar to below picture.
![image](https://user-images.githubusercontent.com/25710115/56543546-bffec280-653f-11e9-85ce-5bb18189e0b9.png)

### Actual Result
Only one polygon is created. Each additional polygon that is drawn on a multipolygon field clears the previous/existing polygon.

Am I missing something or is this not yet implemented?

**Comment by yvaucher** [comment]
IIRC this is not implemented. You can only import multi polygons or multi lines objects.

If you need such edition with precision like in your image you might prefer to use an other tools to generate the geometries.
