### ISSUE TITLE
[12.0] base_geoengine Installation Issues

### ISSUE THREAD

**Issue by aaakevin** [OCA/geospatial#207]
module: base_geoengine, base_geoengine_demo
version: 12.0

Problem:
- Follow module installation of base geoengine, but fail to install on Odoo12C and Odoo12E;

Below is the error screenshot while install geo modules.
Please advise solution of installation. 
Many thanks!

![图片](https://user-images.githubusercontent.com/9838403/61181360-30f1da00-a658-11e9-8e55-02fdb03ff799.png)

**Comment by yvaucher** [comment]
Hello @aaakevin some news on this.

This error has most probably been fixed by https://github.com/OCA/geospatial/commit/32f980fa7a0b6b48a6b6f6c5ed687cbebfc79311

**Comment by aaakevin** [comment]
Thanks for your information.

**Comment by aaakevin** [comment]
> Hello @aaakevin some news on this.
> 
> This error has most probably been fixed by [32f980f](https://github.com/OCA/geospatial/commit/32f980fa7a0b6b48a6b6f6c5ed687cbebfc79311)

 Thank you for your information.
