### ISSUE TITLE
[11.0] Javascript error : this.map is null

### ISSUE THREAD

**Issue by kostakristi** [OCA/geospatial#210]
module: base_geoengine
version: 11.0

**Steps to reproduce**
- ...

**Current behavior**
I install base_geoengine and base_geoengine_demo. when i open geoengine view in ZIP and Retail Machine nothing showed . if i open list view and try to open geoengine view again error is occured. I inspect code i little bit and i think that on_attach_callback function in file geoengine_renderer.js not executed . that's why this.map is null in all other functions
![error](https://user-images.githubusercontent.com/38421558/62688460-2b728000-b9c9-11e9-8e07-1b8428d23b38.png)

**Expected behavior**

**Comment by yvaucher** [comment]
@kostakristi thanks for reporting, I just checked on runbot and cannot reproduce your issue:

Have you tried with a newer version of geoengine?

https://runbot.odoo-community.org/runbot/repo/github-com-oca-geospatial-115
