### ISSUE TITLE
install base_geoengine_demo has error after uninstall base_geoengine_demo

### ISSUE THREAD

**Issue by gitlcp** [OCA/geospatial#212]
![image](https://user-images.githubusercontent.com/34472501/62921749-2c961980-bddc-11e9-9cca-ad56bd0cc319.png)

 
 
###  **Install base_geoengine_demo again to see foreign key constraint problem**can you help me,thank you vary much

**Comment by gitlcp** [comment]
The id of the_geom in ir_model_fields before uninstallation is 2544, but the id is 5430 when uninstalled, so 2455 cannot be found.

![image](https://user-images.githubusercontent.com/34472501/62924889-b09fcf80-bde3-11e9-93d3-851ad3628faa.png)

**Comment by yvaucher** [comment]
@gitlcp you probably want to delete the vector layers and raster layers of base_geoengine_demo by hand or by sql querries.

It seems it tries to delete the fields before the views.
