### ISSUE TITLE
Import external data

### ISSUE THREAD

**Issue by h-stivalet** [OCA/geospatial#214]
Hi guys my apologies if this is not the right place to ask for support but I didn't found any oficial place to do that...so well.

I had imported the raw data from a couple of GeoJson format files with SRID 4326 these are polygons from my city with some extra data.

I had changed in base_geoengine/fields.py the SRID:
`_slots = {
        'dim': 2,
        'srid': 4326,
        'gist_index': True,
        'manual': True,
    }`

And my model looks like this:

`class ageb(geo_model.GeoModel):
    _name = "geo_data.ageb"
    _rec_name = "ageb"
    ageb = fields.Char(string="AGEB")
    ageb_polygon = geo_fields.GeoPolygon('AGEB POLYGON', srid=4326)
    poblacion = fields.Integer(string="Ploblación")
    indice_marginacion = fields.Selection([(1,'Muy bajo'),(2,'Bajo'),(3,'Medio'),(4,'Alto'),(5,'Muy alto')], string="Índice de Marginación")`

After installing the module, in the odoo database table, my polygon field (ageb_polygon) has the right SRID.

So I continued and imported all the geojson data I mentioned before. After this in the spatial view included in pgadmin4 (also on dbeaver) I'm able to see the polygons correctly drawn on my city.

But in the **odoo view** the polygons are not in the right place of the map. Also, from here, if I insert a new polygon it's drawn correctly in this odoo view but it's saved with a different coordinates (or projection) in the DB table therefore it's interpreted wrong in an external map and I can't do intersection queries.

What is the right approach to archive full compatibility with this plugin if I want to continue using SRID 4326 (GPS coordinates) from the original data (no conversions) and see the right location in my Odoo view. I also tried doing a global replace of srid 900913 for 4326 in the plugin files but it didn't help. This is my Odoo view:

`

    
    <record id="solicitud_obra_ageb_view" model="ir.ui.view">
      <field name="name">solicitud.obra.ageb.view.form</field>
      <field name="model">geo_data.ageb</field>
      <field name="arch" type="xml">
        <form string="" delete="0" duplicate="0">
          <sheet>            
            <group>
              <field name="ageb"/>
              <field name="poblacion"/>
              <field name="indice_marginacion"/>
            </group>
            <group>
              <field name="ageb_polygon" widget="geo_edit_map"/>
            </group>
          </sheet>
        </form>
      </field>
    </record>

    
    <record id="ir_ui_view_solicitud_obra_ageb" model="ir.ui.view">
      <field name="name">solicitud.obra.ageb.geo_view</field>
      <field name="arch" type="xml">
        <geoengine version="7.0">
          <field name="ageb"/>
          <field name="poblacion"/>
          <field name="indice_marginacion"/>
          <field name="ageb_polygon"/>
        </geoengine>
      </field>
      <field eval="16" name="priority"/>
      <field name="model">geo_data.ageb</field>
    </record>
    <record id="geoengine_raster_solicitud_obra_ageb" model="geoengine.raster.layer">
      <field name="raster_type">osm</field>
      <field name="name">AGEB</field>
      <field name="view_id" ref="ir_ui_view_solicitud_obra_ageb"/>
      <field eval="0" name="overlay"/>
    </record>`

Many thanks in advance. And I understand if the question is deleted. My Odoo version is 11 and geospatial version is base_geoengine-11.0.1.0.0.

**Comment by h-stivalet** [comment]
Well if somebody is having the same issue this not the right solution, this is only my temporary workaround:

`Code:

    class ageb(geo_model.GeoModel):
    _name = "geo_data.ageb"
    _rec_name = "ageb"

    ageb = fields.Char(string="AGEB")
    ageb_polygon = geo_fields.GeoPolygon('AGEB POLYGON', srid=4326)
    poblacion = fields.Integer(string="Ploblación")
    indice_marginacion = fields.Selection([(1,'Muy bajo'),(2,'Bajo'),(3,'Medio'),(4,'Alto'),(5,'Muy alto')], string="Índice de Marginación")

    @api.model
    def create(self, values):
        if 'ageb_polygon' in values and values['ageb_polygon'] != '':
            values['ageb_polygon'] = self.ConvertGeoJson(values['ageb_polygon'], 3857, 4326)
        return super(ageb, self).create(values)

    @api.multi
    def write(self, values):
        if 'ageb_polygon' in values and values['ageb_polygon'] != '':
            values['ageb_polygon'] = self.ConvertGeoJson(values['ageb_polygon'], 3857, 4326)
        return super(ageb, self).write(values)

    @api.multi
    def read(self, fields=None, load='_classic_read'):
        record = super(ageb, self).read(fields, load=load)
        if len(record) == 1 and 'ageb_polygon' in record[0] and record[0]['ageb_polygon'] != '':
            record[0]['ageb_polygon'] = self.ConvertGeoJson(record[0]['ageb_polygon'])
        return record

    def ConvertGeoJson(self, gjson, from_srid=4326, to_srid=3857):
        #This function converts the projection (SRID)  of a GeoJson point, line or polygon using postgis as a tool
		if not isinstance(gjson, str) or gjson == '':
			return ''
		query = "select ST_AsGeoJSON(st_transform(st_setsrid(st_geomfromgeojson('" + gjson + "')," + str(from_srid) + ")," + str(to_srid) + "))"
		self._cr.execute(query)
		data = self._cr.fetchone()
		if data:
			gjson = data[0]
		return gjson
`

**Comment by yvaucher** [comment]
@h-stivalet hello, this is the right place.

This very sounds like a mismatch between projection of the vector layer compared to the raster layer.
As you use OSM map layer, it is indeed using EPSG:3857 (former EPSG:900913)
Normally setting the projection on the field should be enough, and the module should do the reprojection for you. If it doesn't that could be a bug.

The code that should manage the reprojection is there in v11.

https://github.com/OCA/geospatial/blob/11.0/base_geoengine/static/src/js/widgets/geoengine_widgets.js#L281-L284

BTW, you shouldn't have to modify

`_slots = { 'dim': 2, 'srid': 4326, 'gist_index': True }`

`_slots` defines attributes of the field and default values.

For the srid you have an attribute on the fields you declared.

```python
ageb_polygon = geo_fields.GeoPolygon('AGEB POLYGON', srid=4326)
```

**Comment by dek-odoo** [comment]
Sorry, I am late to party, but you can change  EPSG format of coordinates to "urn:ogc:def:crs:EPSG::3857" i.e. 3857 as Yannick suggested. You can convert it online or if you are exporting it from a software like QGIS, you can change EPSG format before exporting.

In addition you can also have a look here -
https://github.com/dek-odoo/odoo-import-scripts/tree/master/gis_geojson_odoo_import - this might help

My two cents

**Comment by cristhianclv70** [comment]
Hello, have you been able to solve it in any way?

**Comment by dek-odoo** [comment]
Yes, it is absolutely possible.

**Comment by cluzonek** [comment]
> Yes, it is absolutely possible.
Hello, in my case, it happens that when I create the SRID and I want to show my map with OpenStreetMap, the polygons and points are shown in another location, maybe something is missing,

I am currently defining the field as follows:

the_geom = fields.GeoPolygon('Predio',srid=32717)

**Comment by cluzonek** [comment]
> Yes, it is absolutely possible.

Hello, in my case, it happens that when I create the SRID and I want to show my map with OpenStreetMap, the polygons and points are shown in another location, maybe something is missing,

I am currently defining the field as follows:

the_geom = fields.GeoPolygon('Predio',srid=32717)

**Comment by cristhianclv70** [comment]
> Yes, it is absolutely possible.

Hello, in my case, it happens that when I create the SRID and I want to show my map with OpenStreetMap, the polygons and points are shown in another location, maybe something is missing,

I am currently defining the field as follows:

the_geom = fields.GeoPolygon('Predio',srid=32717)

**Comment by dek-odoo** [comment]
You need the correct EPSG format probably, you need to make sure both coordinates use same EPSG, both means: 1: Odoo/OCA modules using 2: coordinates you are supplying

So if both EPSG formats are same then issue should not happen.
