### ISSUE TITLE
displaying map in geoengine

### ISSUE THREAD

**Issue by Rachida-Ouni** [OCA/geospatial#220]
hello, I'm using the geoengine module in my project of master degree. I'd like to display my own devices, and draw lines on the map..can you help me to do this something

**Comment by Rachida-Ouni** [comment]
![Capture d’écran de 2019-10-07 11-14-16](https://user-images.githubusercontent.com/56492852/66714439-370e6880-edb7-11e9-9081-e119b2c8e744.png)

**Comment by yvaucher** [comment]
@Rachida-Ouni reading from your error message I suppose you are creating a field from the interface as it starts with `x_`.

This is currently not supported.

You may want to create your own module using geometry fields.
I suggest you to take the demo module as reference:

https://github.com/OCA/geospatial/tree/12.0/base_geoengine_demo

**Comment by Rachida-Ouni** [comment]
hello , Yannick
I will display devices with their attributes on the map in a well-defined
area, in addition, I will draw optical fiber lines on the map ... so layers
are formed on the map.
can you help me pls
thanks

Le ven. 18 oct. 2019 à 18:43, Yannick Vaucher <notifications@github.com> a
écrit :
