### ISSUE TITLE
[12.0] map_info_box shows '[object Object]' for related fields

### ISSUE THREAD

**Issue by sciallo** [OCA/geospatial#224]
This worked on 9.0 it doesn't on 12 (see screenshot)
Model:
```
 ...
class ProjectTaskMaps(models.Model):
    _inherit = 'project.task'
    _name = 'project.task'
    
    geo_point = fields.GeoPoint('Site coordinates', related='site_id.point')
... 
```
(site_id is a many2one in project.task relating to a sites table with geopoint field)

View:
```
...
    <record id="ir_ui_view_sites_task_maps_view" model="ir.ui.view">
        <field name="name">Tasks view</field>
        <field name="arch" type="xml">
            <geoengine version="7.0">
            	<field name="site_id"/>
                <field name="name"/>
                <field name="project_id"/>
                <field name="user_id"/>
                <field name="stage_id"/>
                <field name="geo_point"/>
            </geoengine>
        </field>
        <field eval="16" name="priority"/>
        <field name="model">project.task</field>
    </record>
...
```
![snapshot2](https://user-images.githubusercontent.com/17577898/67020547-5e717800-f0cc-11e9-908a-0601d32efbef.png)

I apologize if it's something obvious.... I'm slowly learning

**Comment by yvaucher** [comment]
@sciallo Thanks for reporting, which version are you using ? 12.0 ?

EDIT: 12.0 indeed.

**Comment by sciallo** [comment]
is this related to #198 ? Should I need to create new related fields in my model as a work around or can it be fixed to work like it used to?
