### ISSUE TITLE
geoengine

### ISSUE THREAD

**Issue by Rachida-Ouni** [OCA/geospatial#227]
hello, 
I will display devices with their attributes on the map in a well-defined area, in addition, I will draw optical fiber lines on the map ... so layers are formed on the map.
I will use the geoengine module to create the fiber optic network of a company ...
this network contains equipment of different types ..
this equipment must be classified for example: the access network equipment layer contains the IPMSAN and SRO equipment, NodeB ..
the civil engineering layer contains the pipes and the fiber optic layer contains the fiber optic cables.
every equipment to these data ...
do not forget that this equipment must be geolocated
pls help me thanks

**Comment by yvaucher** [comment]
Hello @Rachida-Ouni , sorry for not responding earlier. You might want to narrow your questions to more specific questions.
Are you having trouble to create a module with an odoo objects that has a GeoLine field?
