### ISSUE TITLE
V8 migration

### ISSUE THREAD

**Issue by lmignon** [OCA/geospatial#23]
Works started on https://github.com/acsone/geospatial/tree/8.0-migrate-from-7.0

**Comment by lmignon** [comment]
Current status:
- [x] Forward port changes from PR #16 
- [x] Defines Fields for specialized geo columns 
- [x] Migrate to the new API
- [ ] Extract description in `__openerp__.py` to README.rst
- [ ] Use an init hook to initialize postgis extension at install
- [ ] Move icons to static/description
- [ ] Fix issues when google is used as Raster Layer Type
- [ ] Fix issues when the map is displayed for a specific field. (the label is not visible the map takes the whole width)

At this stage addons are usable in V8 but some remaining issues are to be fixed. However, two bugs in Odoo prevent proper use. To work, you need to merge the following 2 branches.
-   https://github.com/acsone/odoo/tree/8.0-fix-5616-ir_model_fields-from-fields (PR odoo/odoo/pull/5618)
-  https://github.com/acsone/odoo/tree/8.0-fix-use_symbol-c-in-sql-create (PR odoo/odoo/pull/5620)

**Comment by codeadict** [comment]
Hey @lmignon im wanting to work on this  issues

**Comment by lmignon** [comment]
@codeadict the work is done. Take a look at https://github.com/OCA/geospatial/pull/24. But the field definitions are broken due to a recent change in odoo.

**Comment by codeadict** [comment]
cool hope this issues get merged soon y u can merge also #24, by the way
are you using openlayers3 or still old one??

2015-03-27 14:10 GMT-05:00 Laurent Mignon (ACSONE) <notifications@github.com

> :
> 
> @codeadict https://github.com/codeadict the work is done. Take a look
> at #24 https://github.com/OCA/geospatial/pull/24. But the field
> definitions are broken due to a recent change in odoo.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OCA/geospatial/issues/23#issuecomment-87061116.

## 

_Dairon Medina CaroOpenSource Consultantwww.gydsystems.com
http://www.gydsystems.com__email:_ info@gydsystems.com
_weblog:_ http://www.dairon.org
_mobile:_ _(+593)_-987612278
_LinkedIn:_ http://linkedin.com/in/codeadict
_GitHub:_ https://github.com/codeadict
_Skype:_ codeadict
_Twitter:_ @codeadict

**Comment by lmignon** [comment]
@nbessi This one can be closed :smirk:

**Comment by nbessi** [comment]
@lmignon done :wink:
