### ISSUE TITLE
[12.0] Field `geo_point` does not exist may create geofields 

### ISSUE THREAD

**Issue by EBII** [OCA/geospatial#247]
hello 
i try to port geoengine_partner from 11 to 12. 
all seems ok but never create the fields 

Field `geo_point` does not exist
so in model just this 
class ResPartner(geo_model.GeoModel):
    """Add geo_point to partner using a function filed"""
    _inherit = "res.partner"
    geo_point = fields.GeoPoint("Address coordinates")

try on other model with partner_id = fields.Many2one(comodel_name='res.partner')
AttributeError: module 'odoo.addons.base_geoengine.fields' has no attribute 'Many2one'

like with _inherits model

**Comment by yvaucher** [comment]
@EBII Since 12.0 we use the base model inheritance. Thus, you need to change `geo_model.GeoModel` to `models.Model`

Have a look at the demo module:
https://github.com/OCA/geospatial/blob/12.0/base_geoengine_demo/models/retail_machine.py

**Comment by EBII** [comment]
hello, 
Thanks @yvaucher, i saw that but trouble still here.. 
i change 2 thinks to install correctly so i can not say... 

-  AddGeometryColum is mark as deprecated so i replace in geo_db.py with 
https://postgis.net/docs/AddGeometryColumn.html
sql = ("ALTER TABLE {} ADD COLUMN {} geometry({},{})".format(tablename,columnname,geotype,srid))
cr.execute(sql)

- geo_point to geo_partner because it seems to be key-word.
