### ISSUE TITLE
[12.0] Assertion failed. See https://openlayers.org/en/v3.20.1/doc/errors/#25 for details

### ISSUE THREAD

**Issue by MagnusKriel** [OCA/geospatial#252]
Specified a map view using this XML definition:
`  <record id="geo_data_point_map_view" model="ir.ui.view">
    <field name="name">Geo Data Point Map View</field>
    <field name="arch" type="xml">
      <geoengine>
          <field name="geo_point"/>
      </geoengine>
    </field>
    <field name="model">geo.data.point</field>
    <field name="default_extent">18344886.788442, -5943743.319455, 19954344.856015,  -4099470.700991</field>
  </record>`
The default_context I specify is a rectangle around New Zealand using EPSG:900913 projection.
When opening the view in edit mode to create a new record (no data point set as it is a new record) I get this error in the browser:
Assertion failed. See https://openlayers.org/en/v3.20.1/doc/errors/#25 for details.

The map then renders at some other location:
![image](https://user-images.githubusercontent.com/20549666/79442002-0cce8980-802c-11ea-9f7f-fd3693bd78a4.png)

If not specifying the default_context it works but default extent is over Europe.

**Comment by MagnusKriel** [comment]
Found the cause of this issue:
in geoengine_widgets.js, line 121 (Odoo12 branch):
`_updateMapEmpty: function () {
            var map_view = this.map.getView();
            // Default extent
            if (map_view) {
                var extent = this.defaultExtent.split(', ');
                map_view.fit(extent, {maxZoom: this.defaultZoom || 5});
            }
        },`
The extent is a list of strings and when it is passed to the assert function for validation:
`ol.extent.isEmpty = function(extent) {
  return extent[2] < extent[0] || extent[3] < extent[1];
};`
It does a string compare instead of intended float compare.
This is why this extent fails:
`["18344886.788442", "-5943743.319455", "19954344.856015", "-4099470.700991"]`

**Comment by yvaucher** [comment]
@MagnusKriel nice catch!

Shouldn't be too hard to fix.

For the default extent, would make sense to place it at 0,0 and move the europe default_extent in the geoengine demo module.
