### ISSUE TITLE
AttributeError: module 'odoo.fields' has no attribute 'GeoPoint'

### ISSUE THREAD

**Issue by TLmaK0** [OCA/geospatial#258]
I'm trying to add a GeoPoint to an existing model in odoo 12 addon with:

```
from odoo import models, fields, api 

class Location(models.Model):
    _inherit = 'stock.location'

    position = fields.GeoPoint()
```
I have installed base_geoengine from https://apps.odoo.com/apps/modules/12.0/base_geoengine/
and added ```base_geoengine``` to my ```__manifest__``` dependencies. But as soon I have started the odoo server it raises:

`AttributeError: module 'odoo.fields' has no attribute 'GeoPoint'`

**Comment by yvaucher** [comment]
The apps module should be synced with github. Thus you should have the last version.
And your code seems correct to me.

It seams that `base_geoengine` is somehow not loaded.

Maybe you can try to install `base_geoengine_demo` to compare. If this module doesn't install it's an issue on your installation (module not loaded or missing), if the module installs, you have an error somewhere in your custom module, or we have a bug on inheritance.

**Comment by Bhathu30** [comment]
Even me also facing the same issue "**AttributeError: 'GeoPoint' object has no attribute 'dim'**". can anyone help me to find it out.

**Comment by yvaucher** [comment]
@Bhathu30 your issue seems unrelated.

In your case it's the attribute's attribute that is not available.

Do you have a more complete stack trace on the issue?
