### ISSUE TITLE
Backup database with postgis and restore it in another instane

### ISSUE THREAD

**Issue by hyzoom** [OCA/geospatial#278]
Hi
I have the following scenario
- installing odoo 10 instance, install the required packages and postgis extension
- take database backup from this instance and try to restore it in another instance
- database is corrupted even if I added extension to the new database

What shall I do to prevent database corruption after restore in the new instance?

Thanks

**Comment by yvaucher** [comment]
I have some doubts it's related to PostGIS, maybe more postgres. And how the dump was created.

You should check on Postgres community instead.

**Comment by hyzoom** [comment]
> I have some doubts it's related to PostGIS, maybe more postgres. And how the dump was created.
> 
> You should check on Postgres community instead.

Thanks

The problem is restoring with non postgres superuser so there were corruption somehow in accessrights, I dont know!
BTW when I gave the user who restore the db superuser it worked fine
