### ISSUE TITLE
How to use Distant wms

### ISSUE THREAD

**Issue by cristhianclv70** [OCA/geospatial#283]
como usar Distante wms

Hello, I am seeing the d_wms option in Odoo 12, and I cannot configure it I have tried to add a geoserver wms, please help,

**Comment by yvaucher** [comment]
I'm afraid this option is a dead option on the Raster layer there is no code associated with `d_wms` option.

When selection `d_wms` it was showing the `url` field. But the visibility of the `url` field was changed with introduction of the wmts feature. I doubt if it has even been implemented in the past.

Changed in 22ae3b79fbfc373a2aeae2b1b4e096b9bc732dde
