### ISSUE TITLE
[RFC] geoengine_partner : geo_point not linked to partner_latitude / partner_longitude fields

### ISSUE THREAD

**Issue by legalsylvain** [OCA/geospatial#285]
Hi all.

First, thanks for all the geospatial modules I'm just discovering.

I have a naive question : AFAIK : 
- the odoo/addons module ``base_geolocalize`` introduces 2 fields.Float (``partner_latitude``, ``partner_longitude``). ([Ref Code](https://github.com/odoo/odoo/blob/12.0/addons/base_geolocalize/models/res_partner.py#L62)). Those fields can be computed from the adress of the partner (via google API, or via openstreetmap API, if ``base_geolocalize_openstreetmap`` is installed)
- the OCA module ``geoengine_partner`` introduces a fields.GeoPoint (``geo_point``) that is, As far as I understand a couple of latitude and longitude. ([Ref Code](https://github.com/OCA/geospatial/blob/12.0/geoengine_partner/models/partner.py#L11))

However those two concepts don't seem to be linked, and updating ``partner_latitude`` and ``partner_longitude`` doesn't change ``geo_point`` value. (the opposite does not work either).

I don't understand why. Did I missed something ? 

Note : tested on Odoo/12.0

Thanks !

**Comment by yvaucher** [comment]
@legalsylvain , you are right geo_point is a position. In addition it carries the projection in srid. Whereas I assume `partner_longitude` and `partner_satitude` contains always GPS data.

You might want to check on 13.0 branch:
https://github.com/OCA/geospatial/blob/13.0/geoengine_base_geolocalize/models/res_partner.py#L81

EDIT: bad link

**Comment by legalsylvain** [comment]
Hi @yvaucher. Thanks a lot for mentionning ``geoengine_base_geolocalize``. it seems to be the bridge I was looking for.

If I understand correcty with a lattitude and longitude, this module compute a GeoPoint, but the reverse is not True.
So for the module you are mentionning, Geopoint is so readonly. 

I'll backport this module in V12 so.

thanks.

**Comment by yvaucher** [comment]
The Geopoint is a computed field in that case, thus yes, readonly.
What is missing is a reverse function.

It probably requires to read the geopoint and transform it to GPS (EPSG:4326).

with pyproj:

https://pyproj4.github.io/pyproj/stable/api/proj.html?highlight=transform#pyproj.Proj.transform

``` python
    from pyproj import Transformer

    odoo_proj = 'epsg:<TBD>'
    gps_proj = 'epsg:4326'
    transformer = Transformer.from_crs(odoo_proj, gps_proj)
    
    gps_point = transformer.transform(
        lon,
        lat,
    )
```

`<TBD>` Not sure how to transform the `srid` to `epsg` but I'm sure an other lib is there to do that, or even maybe `pyproj` is able to handle srid.

--

While you are at it, this might interest you https://github.com/OCA/geospatial/issues/171
