### ISSUE TITLE
Change projection in ir.ui.view error getExtent

### ISSUE THREAD

**Issue by cristhianclv70** [OCA/geospatial#301]
Hello I am having a problem when in the view "ir.ui.view" I change the projection from EPSG: 3857 to EPSG: 32717, since by default it is created with projection 3857, however I want to work with 32717

when opening the field_geo form, the error it presents is:

"Uncaught TypeError: projection.getExtent is not a function"

**Comment by cristhianclv70** [comment]
I rephrase my question:

I'm using
the_geom = fields.GeoPolygon ('Estate', srid = 32717)

But when presenting on the map, my polygons present them in another location.
and in my "ir.ui.view" it is with Projection EPSG: 3857


![projection](https://user-images.githubusercontent.com/45044175/144777533-feaa5d21-a387-41c4-8960-fff468bcdbe5.png)

**Comment by AaronDeveloperHP** [comment]
i'm having the same problem, i want to use EPSG:4326 but I can't change the projection
