### ISSUE TITLE
Can I embed a geoengine view in a form view?

### ISSUE THREAD

**Issue by CorridorAppalachien-Admin** [OCA/geospatial#317]
Use case: I would like to display geometries related to records from a Many2many field.
"geo_edit_map" widget displays a single record.

Ideally, I would embed the geoengine view inside a form view and apply a domain to the geoengine view according to the Many2many field. Is this possible?

**Comment by yvaucher** [comment]
Currently, I don't think it's possible. I'm not sure what was done for kanban and list view to make them embed-able.
