### ISSUE TITLE
NameError: name 'asShape' is not defined

### ISSUE THREAD

**Issue by halie412** [OCA/geospatial#318]
<!-- Provide a general summary of the issue in the Title above.
In version 2.0.0 launched on 12/12/2022 asShape was deprecated

## Module
base_geoengine

## Describe the bug
base_geoengine/geo_helper/geo_convertion_helper.py line 24 

## To Reproduce
**Affected versions**:
I test on version 14

**Additional context**
Solved this using last stable version of Shapy 1 (1.8.5) with

pip uninstall shapely
pip install shapely==1.8.5

**Note**
I posted this issue because of would be usseful for someone, please mark as solved

**Comment by halie412** [comment]
On version 2.0 of 'shapely' was deprecated 'asShape'

this was solved whith:
pip uninstall shapely
pip install shapely==1.8.5

**Comment by mathben** [comment]
https://github.com/shapely/shapely/pull/961/files

```
   .. deprecated:: 1.8
       The proxy geometries (adapter classes) created by this function are
       deprecated, and this function will be removed in Shapely 2.0.
       Use the `shape` function instead to convert a GeoJSON-like dict
       to a Shapely geometry.
```

**Comment by mathben** [comment]
Check #321
