### ISSUE TITLE
Search on non stored field declared with new API fails

### ISSUE THREAD

**Issue by lmignon** [OCA/geospatial#35]
```
offset=offset, limit=limit, order=order, context=context)
```

base_geoengine/geo_operators.py", line 111, in geo_search
    func = _get_geo_func(model, domain)
  File "/home/lmi/projects/openerp/odoo-geospatial/geospatial/base_geoengine/geo_operators.py", line 32, in _get_geo_func
    current_field = model._columns[domain[0]]
KeyError: 'geo_point'

**Comment by nbessi** [comment]
:cry: confirmed
