### ISSUE TITLE
"Localize addresses from GeoNames" menu is broken

### ISSUE THREAD

**Issue by nbessi** [OCA/geospatial#36]

**Comment by alexalv** [comment]
Facing the same issue in v8
![screenshot](https://cloud.githubusercontent.com/assets/450994/14285917/ea39c39e-fb55-11e5-9184-4504591c9bef.png)

**Comment by alexalv** [comment]
I made 
`parent="base_geoengine.geoengine_base_view_menu"`
 in menuitem and added
`<field name="target">new</field>`
 in action, that seem to solve this problem in v8. Result can be seen on the screenshot below.
Should I make a pull-request or this is not a correct way to solve this issue?
![screenshot](https://cloud.githubusercontent.com/assets/450994/14287460/664aa1e2-fb5b-11e5-9249-416c19c986c4.png)

**Comment by yvaucher** [comment]
Hello @alexalv I agree on the need the change the parent of the menu item.

And also as it is a wizard we want it as "new" in a popup.

A PR would be great. And feel free to fix that typo too: "Geolocalize **you** addresses" -> your
Plus I see a boolean field with no label that miss a `<group>` around it.

And the buttons which could be in a `<footer>`.
