### ISSUE TITLE
Error loading geo modules

### ISSUE THREAD

**Issue by ovnicraft** [OCA/geospatial#37]
I am trying to use 7.0
- Checkout 7.0 version
- add geospatial folder to addons-path, loading get this output: https://gist.github.com/anonymous/fa75990cc760a6dfe4ed

So i edit **init** file removing from . and let import FILE an get this error: https://gist.github.com/anonymous/0482cf6222eec11bd225

**Comment by lmignon** [comment]
@ovnicraft Can I close this one?
