### ISSUE TITLE
Unmet dependencies: crm

### ISSUE THREAD

**Issue by akram1** [OCA/geospatial#45]
First module to install of OCA/geospatial is Geospatial support of partners right after fresh build of Odoo July,3 2015. Installing went fine but with some error: CRM and base_geolocalize not installed
geoengine_partner
Uninstall the module failed with Unmet dependencies: crm

So I had to install CRM manually. Uninstall Geospatial support of partners and tried to Geospatial support for base_geolocalize. This installed  base_geolocalize and  partners modules correctly. Every module installed correctly then after except Geo Spatial support demo.
I think modules should take care of dependency.

**Comment by yvaucher** [comment]
Are you sur your path was correctly set for official addons ? crm is part of them.

**Comment by yvaucher** [comment]
Closing as no feedback
