### ISSUE TITLE
Where to host geospatial module related to another OCA project?

### ISSUE THREAD

**Issue by dreispt** [OCA/geospatial#49]
I'm writing a module to add geospatial features to modules from the `OCA/project-service` repo.
Should it be hosted here or there?

**Comment by lmignon** [comment]
@dreispt IMO it should be here. A  first PR #27 exist to geolocalise project.

**Comment by dreispt** [comment]
I slept over this and came convinced otherwise. 
But maybe we're both can be right.
Here is my criteria proposal:
- Geospatial should host the core features plus the extensions to Odoo core addons, such as sale, and project
- Extensions specific (requiring) to other OCA projects should be hosted there.

**Comment by lmignon** [comment]
@dreispt  :+1:  make sense

**Comment by dreispt** [comment]
In project-server, a `location_id` field is added to Tasks, so that you can tell the address where the service is needed. With that and geoengine, we can visualize the open Tasks in a map.
I'll need to make sure the TravisCI setup on tat repo is capable of installing goengine modules.

**Comment by ovnicraft** [comment]
@dreispt i suggest OCA/geospatial-extras enough by now, any can of repo can be hosted there.

**Comment by yvaucher** [comment]
The main issue of what we put where is that it would drag dependencies with it. Thus, I think it's a bad idea to add geospatial modules using geoengine in other existing repositories.

So if it doesn't depend on core addons, I agree with @ovnicraft that we would require another repository.
