### ISSUE TITLE
Script error : This page is trying to load scripts from unauthenticated sources

### ISSUE THREAD

**Issue by rjpathan** [OCA/geospatial#52]
Hello,

I have installed geo modules but some scripts don't load automatically.
Rather I get "This page is trying to load scripts from unauthentic sources". So I have to manually click on "Load unsafe scripts" to allow geo module work.
Please check screenshot attached.

Any suggestions?

Thanks

Regards
Riyaj
![geo_load_err](https://cloud.githubusercontent.com/assets/6248084/9274396/1bd65950-42b3-11e5-8016-f4d841df5274.png)

**Comment by lmignon** [comment]
@rjpathan Is your sources up to date? A fix has been applied in 3c034a8 to avoid this kind of problem.

**Comment by rjpathan** [comment]
I updated my sources (fix was missing), and also upgraded base_geoengine module. But still issue persist.

**Comment by lmignon** [comment]
@rjpathan do you have reloaded the page after the upgrade,  clear the cache of your browser and restarted the server and empty  (Just to be sure that the Js loaded by your browser is up to date)

**Comment by rjpathan** [comment]
Tried with restarting odoo, reloading page, upgrading module and checking again after deleting browser cache. But still error notification shows up.

**Comment by lmignon** [comment]
@rjpathan can you check what's the unauthenticated resources that your browser try to access?

**Comment by rjpathan** [comment]
Sorry, not sure how to find it out. 

On Firefox, it shows different message:
![firefox_geo_err](https://cloud.githubusercontent.com/assets/6248084/9276163/eb17767a-42bf-11e5-9ee3-04d80a221094.png)

**Comment by lmignon** [comment]
@rjpathan In your last screenshot, they are nothing related to geoengine displayed on the page. Do you have the same error when you access others menus on your instance? Without knowing the url that your browser try to access It's hard to find what happens.

**Comment by rjpathan** [comment]
Everything else works fine except that geoengine view and form having geopoint field which raises following js error: (it doesn't allow to create/edit new records and map shows blank)
![geo_err_form](https://cloud.githubusercontent.com/assets/6248084/9276625/c3f54088-42c2-11e5-9cd2-564e9b2d18b6.png)

**Comment by lmignon** [comment]
@rjpathan which version of odoo are you using? 7.0 or 8.0

**Comment by rjpathan** [comment]
I'm using version 8.0

**Comment by lmignon** [comment]
@rjpathan it's really strange is like you use an old version of the geoengine addons... I don't understand what's happen

**Comment by rjpathan** [comment]
I will check again with latest geoengine modules and report back here.

**Comment by rjpathan** [comment]
Hello, today I downloaded latest modules from github branch and created new database (after deleting browser cache). Everything was ok, but then just installed base_geoengine module, and the error appeared as shown in previous messages.

**Comment by lmignon** [comment]
@rjpathan can you check that everything is OK with our test server http://3111947-8-0-6face2.runbot2.odoo-community.org/
May be you can try to replace google by OpenStreetMap as raster layer type in the layer management list. GeoEngine backend -> Raster Layer Management.
May be a stupid question but do you have access to google services in your country?

**Comment by rjpathan** [comment]
Everything works perfect on http://3111947-8-0-6face2.runbot2.odoo-community.org/ 
Let me try with other suggestion i.e. replacing google by OpenStreetMap as raster layer type.

Yes, I can access all google services here.

**Comment by lmignon** [comment]
@rjpathan http://3111947-8-0-6face2.runbot2.odoo-community.org/  is an Odoo 8.0 server with the geoengine 8.0 branch

**Comment by rjpathan** [comment]
Yes, I am using geospatial 8.0 branch on Odoo 8.

**Comment by lmignon** [comment]
@rjpathan What's the result when you replace google by OpeneStreetMap. Is your map displayed? Can you also try to install the geoegine_demon on en empty db without your custom addons?

**Comment by rjpathan** [comment]
If I change raster layer type from google to oms OpenStreetMap then it works. Although, on browser address bar, notification icon remains there for "Load Unsafe scripts".

**Comment by prashant2k15** [comment]
even i having the same problem 
can any one tell me how to solve this?
