### ISSUE TITLE
Missing link to geoengine_geoname_geocoder wizard in v7

### ISSUE THREAD

**Issue by riess82** [OCA/geospatial#53]
I managed to install the prerequisites and the modules in v7 after some trial and error, but i can't display the link for the wizard in the menu.
The headline "Localize addresses from GeoNames" is shown, but there is nothing below.

**Comment by lmignon** [comment]
@riess82 Is your user member of the group 'Geoengine user'  or 'Geoengine admin'?

**Comment by riess82** [comment]
Yes, i am trying with admin user, and checked both checkboxes for Geo user and Geo admin. I can see the menuitems for View Management, for example.

**Comment by lmignon** [comment]
@riess82 Do you have enabled the geocoding on you user's company?

**Comment by riess82** [comment]
Yes, i have. I can even use the wizard when i search the wizard id in the database and type the url manually.

**Comment by riess82** [comment]
Now that i was looking for something else,I found that this is a duplicate from #36
