### ISSUE TITLE
Installation docs insufficient

### ISSUE THREAD

**Issue by COLABORATI** [OCA/geospatial#58]
The installation docs found [here](http://oca.github.io/geospatial/installation.html) are not sufficient. 
Please add a description how to install this product in odoo 8 and odoo 9.

**Comment by lmignon** [comment]
@COLABORATI This module doesn't work on Odoo 9.  Can you elaborate why the doc is not sufficient and describe your problem?
Regards,
lmi

**Comment by COLABORATI** [comment]
It is about installation in odoo 8. 
There are actually _no_ instructions available on how to install this module.
[This](https://www.odoo.com/apps/modules/8.0/base_geoengine/) document has exactly _one_ instruction about installing postgis. It then tells the reader that two python modules have to be installed, but it does not tell the reader how to install them and the documentation stops there. It links to another [document](http://oca.github.io/geospatial/index.html) - there are instructions about prerequisites, which btw will fail on Debian Jessie, because there is no `pip` command.  However there is again _zero_ information about how to install this module - in the [installation](http://oca.github.io/geospatial/installation.html) section of that documentation there are two git commands but then no actual documentation about how to install this module. 

BTW I found the mentioned OCB repo now via ddg, but have no clue what the differences are compared to the original repo, also it is unclear if this is the referenced repo from your docs and if one has to use this repo to get these extensions to work. Please put a _Link_ to that repo to the installation docs. I used the packages that are found on nightly.odoo.org - does your product _not_ work with these packages? This should be written clearly in the docs then.

However, the instructions are far away from complete and do not lead to a running version of your modules if followed. I attached screenshots because I believe there is a high probability that you are seeing some different version of these documents with possibly uncommited and not publicly visible changes that you assume are online but you can not see that public version of the document has near to zero information.

Docs found on https://www.odoo.com/apps/modules/8.0/base_geoengine/ are like this:
![odoo-geospatial-docs-01](https://cloud.githubusercontent.com/assets/6514273/11183034/b2ccb0d8-8c6f-11e5-87fe-19b79af997a5.png)

The minimalistic install instructions on http://oca.github.io/geospatial/installation.html look like this:
![odoo-geospatial-docs-02](https://cloud.githubusercontent.com/assets/6514273/11183033/b2c500e0-8c6f-11e5-8ebd-86dd81f69efc.png)

**Comment by pedrobaeza** [comment]
If you don't know what is pip, you're missing prerequisites that you must already know. README is not a complete, exhaust guide for you to learn you about OS, python, pip, and so on. You must learn this in their respective areas. But if you make a simple search reveals that you only need to do `sudo apt-get install python-pip` for getting this handy and basic python util.

**Comment by lmignon** [comment]
@COLABORATI Thank you for your explanation. The documentation is maybe a little bit developer centric.

The geospatial addons take adavantage of the GIS capabilities available for postgres. The first requirement is to install the postgis (http://postgis.net/) extension for your OS. (http://postgis.net/install/)

Additionally, we use two additional python modules to manage this kink of specific data. Shapely and geojson. These 2 modules are available as standard debian packages

```
apt-get install python-geojson
apt-get install python-shapely
```

At this stage you have almost everything required to use these addons. Unfortunately, a bug into the Odoo core distribution prevents the normal behavior of these addons. Therefore, you need to apply the changes described in the following Pull Request (https://github.com/odoo/odoo/pull/5620) to your installation. Depending of the way you installed Odoo, (git clone/ download / debian dist) you can use specific git command or manually edit the code.

As you know, we do our best to provide some useful addons but as developer, we don't always have the time and/or the resources to provide the right documentation. I'll be happy  to review/merge any PR improving the current situation.

Regards,

**Comment by pedrobaeza** [comment]
I insist: this shouldn't be an extensive/full steps guide for all the basics, because in this way, someone can say that his/her distribution/OS (CentOS, Fedora, Windows...) is not covered and they don't know how to install dependencies. For me, it's enough as is. Maybe point to any useful link or search for knowing more on other topics, but as said, this is very subjected to the several possible options.

**Comment by COLABORATI** [comment]
The important point was: there is still no information about how to install the actual module. 
Of course I understand that not every developer has the capabilities to deliver a professional documentation - I am sure most potential customers do not see this as a problem.

**Comment by pedrobaeza** [comment]
> The important point was: there is still no information about how to install the actual module. 

Just as any other regular Odoo module. This is still out of scope of this repository documentation.
