### ISSUE TITLE
[9.0] [8.0] [7.0] base_geoengine - Google layers are not displayed

### ISSUE THREAD

**Issue by yvaucher** [OCA/geospatial#63]
How to reproduce:

With `geoengine_demo` installed (to have some data to play with).
In raster layer management change a raster layer type to google

Display the map selecting this raster layer

Points or shapes are displayed but there is no map.

**Comment by OEGEM** [comment]
Hi,
same problem even if geoengine_demo is not installed.
Tested with chrome 45 and firefox 42 on ubuntu 14.04

**Comment by yvaucher** [comment]
@OEGEM Sure it is just the step to simply reproduce it. The issue is definitely in `base_geoengine`

I updated my description.

**Comment by ikzent** [comment]
Issue comes from a phase out of the Google API as the standard openlayers java script is versioen 2.13.1 
https://github.com/openlayers/ol2/issues/1450 
Best way to go is use openstreetmap as standaard background

**Comment by yvaucher** [comment]
I put this as a won't fix as we probably want to extract it anyway. The issue is that having google api in base module loads the js even if not using it: https://github.com/OCA/geospatial/issues/95

**Comment by Rachida-Ouni** [comment]
hello, I'm using geoengine module in my project. I want to display, draw my own devices on the map, but I can't do it with this module. so pls help me

**Comment by yvaucher** [comment]
@Rachida-Ouni Please open a new issue and provide more information about what you are trying to achieve.
