### ISSUE TITLE
Can't use backup tools from odoo web database manager

### ISSUE THREAD

**Issue by J1b4y** [OCA/geospatial#68]
Hello,

When we try after install geoengine we can't make a backup with the database manager of odoo : 
Postgres subprocess ('/usr/bin/pg_dump', '--no-owner', '--username=pg-odoo-production', '--file=/tmp/tmpEvloUK/dump.sql', u'production') error 1

and when we try to do a backup in line we have this error: 
pg_dump: [archiver (db)] query failed: ERROR:  permission denied for schema topology
pg_dump: [archiver (db)] query was: LOCK TABLE topology.topology IN ACCESS SHARE MODE

have you a solution or a patch ?

**Comment by J1b4y** [comment]
Ok that not really a issue but more a mistake from the doc:
i think you have to add to your doc the step, parameter your role:

GRANT ALL PRIVILEGES ON                  SCHEMA topology TO role_name;
GRANT ALL PRIVILEGES ON ALL TABLES    IN SCHEMA topology TO role_name;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA topology TO role_name;

this to avoid some bug in script who use pg_dump or other stuff,

thanks

**Comment by treviser** [comment]
`GRANT ALL PRIVILEGES ON SCHEMA topology TO role_name;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA topology TO role_name;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA topology TO role_name;`

Please add this to the doc!!!

**Comment by yvaucher** [comment]
@treviser Your PRs would be welcome on the doc

**Comment by pronexo-argentina** [comment]
In docker you have to enter the container and install postgresql9.5. You have to update psql to 9.5.

1 - #we create a new source to install psql 9.5
vim /etc/apt/sources.list.d/postgresql.list

2 - Insert this  line
deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main 9.5

3 - we download public key to let us lower the psql9.5
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -

4 - Update apt sources
apt-get update

5 - Install 
apt-get install postgresql-9.5
