### ISSUE TITLE
[8.0] GeoEngine not covering the whole page (height)

### ISSUE THREAD

**Issue by ikzent** [OCA/geospatial#69]
When The map is displayed the whole width is covered correctly but the height is not covered completely. How can this be solved

**Comment by yvaucher** [comment]
Please specify the version of Odoo

**Comment by ikzent** [comment]
It concerns the version 8 of Odoo.
I found the code in the javascript but, it seems that openlayers needs at least some information about window size, I put in an Higher value.
/base_geoengine/static/src/xml/geoengine.xml   I changed the height to 800 instead of 500

I will soon publish the code to have a label on a point, at this moment this is not seen.

## 

Eric Smets                                    eric.smets@fks.be mailto:eric.smets@fks.be 
FKS bvba - Formal and Knowledge Systems       http://www.fks.be http://www.fks.be/ /
Schampbergstraat 32                           Tel:  ++32-(0)11-21 49 11
B-3511 Hasselt                                Fax:  ++32-(0)11-22 04 19

-----Oorspronkelijk bericht-----
Afzender: Yannick Vaucher notifications@github.com
Verstuurd: Vrijdag 22 Januari 2016 14:31
Aan: OCA/geospatial geospatial@noreply.github.com
Cc: Eric Smets eric.smets@fks.be
Onderwerp: Re: [geospatial] GeoEngine not covering the whole page (height) (#69)

Please specify the version of Odoo

**Comment by yvaucher** [comment]
I know in 8.0 there was some issue with it. This has been solved in 9.0 though.

Let me know when your PR is ready. Thanks

**Comment by ikzent** [comment]
I will look in the 9 code

## 

Eric Smets                                    eric.smets@fks.be mailto:eric.smets@fks.be 
FKS bvba - Formal and Knowledge Systems       http://www.fks.be http://www.fks.be/ /
Schampbergstraat 32                           Tel:  ++32-(0)11-21 49 11
B-3511 Hasselt                                Fax:  ++32-(0)11-22 04 19

-----Oorspronkelijk bericht-----
Afzender: Yannick Vaucher notifications@github.com
Verstuurd: Vrijdag 22 Januari 2016 14:39
Aan: OCA/geospatial geospatial@noreply.github.com
Cc: Eric Smets eric.smets@fks.be
Onderwerp: Re: [geospatial] GeoEngine not covering the whole page (height) (#69)

I know in 8.0 there was some issue with it. This has been solved in 9.0.

**Comment by yvaucher** [comment]
@ikzent 9.0 migration is there #60 thought it might not help you, there was quite some changes in core module `web`
