### ISSUE TITLE
Map Markers / shapes not being displayed

### ISSUE THREAD

**Issue by dupski** [OCA/geospatial#70]
Hi guys. Thanks for this awesome project!

I'm trying out the v7 branch for a customer that is using OpenERP v7 but we are having an issue where the map displays fine but no markers are shown.

Another symptom is that the Measure Distance function shows the distance but there is no line shown to the cursor when moving the mouse.

I am using PostGIS 2.2 on PostgreSQL 9.1, geojson 1.3.2, Shapely 1.2.14
I have tried in Firefox 44 and Chrome 48

Could you suggest what might not be working? There are no errors in the javascript console and there are entries in the "actives" property of the "geoengine_layers" property.

Thanks!

**Comment by dupski** [comment]
I've now got this working on a clean install of OpenERP v7, so its something to do with our customisations. Please ignore! :)

**Comment by dupski** [comment]
If anyone comes across the same issue, this was caused by an old version of NVD3's CSS (clobbering OpenLayer's SVG images).

Upgraded D3 and NVD3 to the latest versions and problem solved :)

**Comment by yvaucher** [comment]
Thanks for the feedback. Didn't happened to me though.
