### ISSUE TITLE
can we use google map as the base of our map ?

### ISSUE THREAD

**Issue by hengkyzhang** [OCA/geospatial#80]
i want to know regarding legality when we use google map for our module
can we use it without charge (FREE) for our module?

**Comment by yvaucher** [comment]
Hello @hengkyzhang ,

You can find the conditions here: https://www.google.com/intl/en_US/help/terms_maps.html

It depends what you do with it.  But yes it's free of charges.

BTW it doesn't work anyway: #63 so you should probably use OpenStreetMap
