### ISSUE TITLE
[9.0] Base Layer and Overlays are offset on Chrome with browser zoom != 100%

### ISSUE THREAD

**Issue by sciallo** [OCA/geospatial#82]
Installed base_geoengine_demo on freshly created database.

When looking at geoengine view for retailmachine the "dots" move at a different rate than the base map when moving or zooming. same behavior in form widget.

The same happens with ZIP polygons.

**Comment by sciallo** [comment]
Upon further research, I realized it has to do with browser zoom... I was able to replicate in runbot: open a map view and change the zoom in your browser. points or polygons will move at different rate than map. This doesn't happen on openstreetmap.org

**Comment by yvaucher** [comment]
#88 might fix this issue

**Comment by sciallo** [comment]
This fixed it for firefox but NOT for chrome (kubuntu 14.04), haven't tested other browsers yet

**Comment by yvaucher** [comment]
I tested it on:
- Firefox 44.0: it works
- Chromium 48.0.2564.82: it works
- Chrome:  50.0.2661.86: it fails only if zoom is not 100%

Thought on chrome it is not the same issue as we had on firefox. #88 fix an issue with offset on the Y axis. On Chrome it seems that offsets are on X and Y axis. And it acts differently.

**Comment by yvaucher** [comment]
Chrome is acting differently, and makes it very difficult to solve this. I won't be able to fix this for chrome.
