### ISSUE TITLE
V7.0: VIEW_TYPE - Side Effect !!!

### ISSUE THREAD

**Issue by diassynthesis** [OCA/geospatial#9]
Now, after some modifications i can install **base_geoengine** module (i will submit a PR for V7.0).
But there is a strange issue after installing it. 
All seems to working fine, but when restarting the server, i get the following error(and I can no longer log me into the server):
-------Start Error Log:
File "/usr/lib/pymodules/python2.7/openerp/osv/orm.py", line 948, in create_instance
    obj.**init**(pool, cr)
  File "/usr/lib/pymodules/python2.7/openerp/addons/web_dynatree/base.py", line 98, in **init**
    self._columns['type'].selection.append(VIEW_TYPE)
**AttributeError: 'tuple' object has no attribute 'append'**
-----End Log----

**Steps to reproduce:**
1- install web_dynatree (from https://bitbucket.org/anybox)
2- install base_geoengine
3- restart OpenERP

![appen-view_types](https://cloud.githubusercontent.com/assets/3822648/5987822/51cd5236-a941-11e4-82fd-396a94126154.png)

This is also the case with the following modules:
**web_nvd3_chart**
**booking_chart** (https://github.com/trobz/openerp-booking-chart
**web_dynatree_visual_export**

I also think that this will be the case with any installed module dealing with **VIEW_TYPE**

Any idea ?

**Comment by yvaucher** [comment]
@diassynthesis Please have a look at https://github.com/OCA/geospatial/tree/7.0

Geoengine 7.0 was ported few days ago.

Thus I close your issue, feel free to reopen it if you still experience it with current ported version.

**Comment by diassynthesis** [comment]
still the same issue after 3 years.
@benwillig i can't find this commit.
