### ISSUE TITLE
Installed geo modules, created account on geonames.org , Don't see a map.

### ISSUE THREAD

**Issue by diezcode** [OCA/geospatial#93]
Hi, I intsalled all geo modules with all server depencies, I created an account on geonames.org, then I activatet the account.
In odoo8 I set  a new systemparameter = geoengine_geonames_username = (accountname of geonames)

Then when I want to see the map on the customers I see the buttons, but it's empty, I don't see a map. whats wrong?

**Comment by diezcode** [comment]
How Can I see the Partner Locations? Any Settings I need

**Comment by diezcode** [comment]
How can I see a partner in the map ?

**Comment by yvaucher** [comment]
In odoo 8.0 google layers are not working. Please try with openstreet map instead.

**Comment by diezcode** [comment]
thanks @yvaucher and how can I set a partners location on this openstreet map

**Comment by yvaucher** [comment]
@diezcode Not sure what you are asking. You need a geo field on your partner and to setup your vector layers and your views.

You will find an example in this module: https://github.com/OCA/geospatial/tree/8.0/base_geoengine_demo

You will also find the prerequisite here:
http://oca.github.io/geospatial/index.html

**Comment by yvaucher** [comment]
I realize you were probably talking about `geoengine_geoname_geocode` which inherits `geoengine_partner`
this was also asked in #126 

Closing as first question was answered
