### ISSUE TITLE
Loading of googleapis

### ISSUE THREAD

**Issue by guewen** [OCA/geospatial#95]
Is there any reason to load a javascript from maps.googleapis.com?  https://github.com/OCA/geospatial/blob/44d492b9a3d59407b294ed252641b42107742de0/base_geoengine/views/base_geoengine_view.xml#L19

**Comment by lmignon** [comment]
@guewen To avoid licence infringement. You can't redistribute code from google. But if the support of googlmap is dropped, this line can be removed.

**Comment by guewen** [comment]
Yes indeed, but I thought the support of google map had already been dropped.

**Comment by yvaucher** [comment]
In fact it was only disabled.

https://github.com/OCA/geospatial/blob/9.0/base_geoengine/geo_view/geo_raster_layer.py#L28

There are some issue related to it in 8.0. This is probably because it was default value and not working. As noone started to fix it I think we can purge it.

**Comment by ghost** [comment]
This comes due to the change in api google version (the version in odoo is not supported any more by google)

**Comment by yvaucher** [comment]
This was removed in version 10.0
