### ISSUE TITLE
Is this ready for production

### ISSUE THREAD

**Issue by hengkyzhang** [OCA/geospatial#97]
is this module ready for production use?

**Comment by yvaucher** [comment]
It is ready depending on your needs. We currently use base_geoengine on 6.1 and on 9.0 on production as a base for specific modules.

For readonly geospatial data it is fine from 6.1 to 8.0. If you want to edit data some improvements have been done in 9.0 version and thus is more suitable.

Feel free to test on http://3149015-9-0-172cc9.runbot2.odoo-community.org/web/login
